### ISSUE TITLE
NotImplementedError: "intersectBed" does not appear to be installed or on the path, so this method is disabled.  Please install a more recent version of BEDTools and re-import to use this method.

### ISSUE THREAD

**Issue by burcakotlu** [arq5x/bedtools#152]
I installed pybedtools    0.8.0

################################
import pybedtools

a = pybedtools.example_bedtool('a.bed')
b = pybedtools.example_bedtool('b.bed')
a_and_b = a.intersect(b)
################################

################################
It gives the response below: 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/burcak/anaconda3/lib/python3.7/site-packages/pybedtools/bedtool.py", line 840, in decorated
    result = method(self, *args, **kwargs)
  File "/home/burcak/anaconda3/lib/python3.7/site-packages/pybedtools/bedtool.py", line 212, in not_implemented_func
    raise NotImplementedError(help_str)
NotImplementedError: "intersectBed" does not appear to be installed or on the path, so this method is disabled.  Please install a more recent version of BEDTools and re-import to use this method.
################################

**Comment by ZHIDIHUAYUAN** [comment]
I got the same error. Have you figure it out?

**Comment by ZHIDIHUAYUAN** [comment]
I encountered the same problem. Did you solve it?
